"""Turning an understood problem into an executable dependency graph.

A deliberate design decision, and the one most likely to be challenged in
review: the plan topology is derived deterministically from the analysed
problem rather than generated by a model.

The reasoning is that a plan is a control-flow artifact, not a creative one. In
a regulated environment you have to be able to answer "why did the system do
these steps, in this order" and "would it do the same thing again". A model
that emits a different graph on every invocation cannot answer either question,
and the audit trail of a non-reproducible plan is worth very little. So the
judgement lives where judgement belongs: the model does the analysis, and the
topology follows from that analysis by rules that a human can read.

Re-planning is not a contradiction of that. It is the same rules applied again
to evidence that did not exist when the first plan was made.
"""

from __future__ import annotations

from dataclasses import dataclass, replace

from keel.models import (
    EngineeringProblem,
    ImpactLevel,
    ModelTier,
    NodeSpec,
    Plan,
    RetryPolicy,
    ScenarioKind,
    StageKind,
)

# Node ids are stable and human-readable because they appear in the audit log,
# the HTML report, and the approval prompts a person actually reads.
IMPACT = "impact-analysis"
DESIGN = "design"
IMPLEMENT = "implement"
AUTHOR_TESTS = "author-tests"
DOCUMENT = "document"
VERIFY = "verify"
REVIEW = "review"
RELEASE = "release-check"
REFACTOR = "refactor-seam"


@dataclass(slots=True)
class RevisionRequest:
    """An explicit, auditable description of why a plan is changing."""

    reason: str
    add: list[NodeSpec]
    remove: set[str]
    rewire: dict[str, list[str]]  # node id -> new depends_on


class Planner:
    def __init__(self, capabilities: set[str] | None = None):
        """`capabilities` are the skill ids discovered from Agent Cards.

        Passing them lets the planner refuse to schedule a stage that no agent
        in the mesh can actually serve, instead of failing at dispatch time.
        """
        self.capabilities = capabilities

    def _available(self, kind: StageKind) -> bool:
        return self.capabilities is None or kind.value in self.capabilities

    def build(self, problem: EngineeringProblem) -> Plan:
        """Derive the initial graph.

        The shape is a diamond on purpose. `implement`, `author-tests` and
        `document` all depend only on `design`, so they run concurrently, and
        `verify` depends on two of them, which makes it a real synchronization
        barrier rather than a decorative one.
        """
        nodes: list[NodeSpec] = []
        brownfield = problem.scenario is ScenarioKind.BROWNFIELD

        design_deps: list[str] = []
        if brownfield and self._available(StageKind.ANALYZE):
            nodes.append(
                NodeSpec(
                    id=IMPACT,
                    kind=StageKind.ANALYZE,
                    description="Identify impacted modules, routes and data flows.",
                    skill_id=StageKind.ANALYZE.value,
                    model_tier=ModelTier.DEEP,
                    entry_rules=["existing_code_present"],
                    exit_rules=["impact_surface_identified"],
                    produces=["impact.json"],
                    rollback=False,  # read-only analysis, nothing to undo
                )
            )
            design_deps = [IMPACT]

        nodes.append(
            NodeSpec(
                id=DESIGN,
                kind=StageKind.DESIGN,
                description="API surface, data model, and the trade-offs behind them.",
                depends_on=design_deps,
                skill_id=StageKind.DESIGN.value,
                model_tier=ModelTier.DEEP,
                exit_rules=["endpoints_defined", "redirect_status_justified"],
                produces=["design.json"],
                rollback=False,
            )
        )

        nodes.append(
            NodeSpec(
                id=IMPLEMENT,
                kind=StageKind.IMPLEMENT,
                description="Generate the service source.",
                depends_on=[DESIGN],
                skill_id=StageKind.IMPLEMENT.value,
                model_tier=ModelTier.DEEP,
                # Touching an existing public API surface is a change-control
                # event, so a human signs off before it happens.
                impact=ImpactLevel.HIGH if brownfield else ImpactLevel.MEDIUM,
                retry=RetryPolicy(max_attempts=2, fallback_hint="simplify_scope"),
                entry_rules=["design_available"],
                exit_rules=["files_written", "no_secrets", "no_destructive_ops"],
                produces=["app source files"],
            )
        )

        nodes.append(
            NodeSpec(
                id=AUTHOR_TESTS,
                kind=StageKind.TEST,
                description="Write tests from the design, including security cases.",
                depends_on=[DESIGN],
                skill_id=StageKind.TEST.value,
                model_tier=ModelTier.DEEP,
                entry_rules=["design_available"],
                exit_rules=["files_written"],
                produces=["test files"],
            )
        )

        if self._available(StageKind.DOCUMENT):
            nodes.append(
                NodeSpec(
                    id=DOCUMENT,
                    kind=StageKind.DOCUMENT,
                    description="README and security posture for the generated service.",
                    depends_on=[DESIGN],
                    skill_id=StageKind.DOCUMENT.value,
                    # Prose from a spec does not need the expensive model. This
                    # is the cost-routing decision made visible.
                    model_tier=ModelTier.FAST,
                    produces=["README.md"],
                )
            )

        nodes.append(
            NodeSpec(
                id=VERIFY,
                kind=StageKind.TEST,
                description="Actually run the generated test suite against the code.",
                depends_on=[IMPLEMENT, AUTHOR_TESTS],
                skill_id=StageKind.TEST.value,
                model_tier=ModelTier.FAST,
                entry_rules=["code_and_tests_present"],
                exit_rules=["tests_executed", "tests_passed"],
                produces=["verify.json"],
                rollback=False,
            )
        )

        nodes.append(
            NodeSpec(
                id=REVIEW,
                kind=StageKind.REVIEW,
                description="Adversarial review of the generated code.",
                depends_on=[VERIFY],
                skill_id=StageKind.REVIEW.value,
                model_tier=ModelTier.DEEP,
                exit_rules=["no_critical_findings"],
                produces=["review.json"],
                rollback=False,
            )
        )

        release_deps = [REVIEW] + ([DOCUMENT] if self._available(StageKind.DOCUMENT) else [])
        nodes.append(
            NodeSpec(
                id=RELEASE,
                kind=StageKind.RELEASE_CHECK,
                description="Release readiness against the acceptance criteria.",
                depends_on=release_deps,
                skill_id=StageKind.RELEASE_CHECK.value,
                model_tier=ModelTier.FAST,
                produces=["release.json"],
                rollback=False,
            )
        )

        return Plan(
            nodes=nodes,
            version=1,
            rationale=_rationale(problem, brownfield),
        )

    def revise(self, plan: Plan, request: RevisionRequest) -> Plan:
        """Produce the next version of a plan.

        Plans are immutable and versioned rather than mutated in place, so the
        audit trail shows what the system intended to do before and after new
        evidence arrived. `supersedes` links the two.
        """
        kept = [n for n in plan.nodes if n.id not in request.remove]

        rewired: list[NodeSpec] = []
        for node in kept:
            if node.id in request.rewire:
                rewired.append(replace(node, depends_on=list(request.rewire[node.id])))
            else:
                # Drop dependencies on nodes that no longer exist.
                deps = [d for d in node.depends_on if d not in request.remove]
                rewired.append(replace(node, depends_on=deps) if deps != node.depends_on else node)

        return Plan(
            nodes=rewired + list(request.add),
            version=plan.version + 1,
            rationale=request.reason,
            supersedes=plan.version,
        )

    def revise_from_evidence(self, plan: Plan, evidence: dict) -> Plan | None:
        """Decide whether runtime findings invalidate the current plan.

        This is the requirement that most implementations skip: the plan is not
        a script decided up front, it responds to what the earlier stages
        actually found. Returns None when the existing plan still holds, which
        matters as much as returning a new one, because re-planning on every
        signal is just thrash.
        """
        findings = evidence.get("impacted_modules") or []
        needs_seam = bool(evidence.get("missing_extension_point"))

        if not needs_seam or REFACTOR in plan.node_ids:
            return None

        seam = NodeSpec(
            id=REFACTOR,
            kind=StageKind.IMPLEMENT,
            description=(
                "Introduce the extension point the change requires. "
                f"Impacted: {', '.join(str(f) for f in findings[:5]) or 'unspecified'}"
            ),
            depends_on=[DESIGN],
            skill_id=StageKind.IMPLEMENT.value,
            model_tier=ModelTier.DEEP,
            impact=ImpactLevel.HIGH,
            entry_rules=["design_available"],
            exit_rules=["files_written", "no_secrets"],
            produces=["refactored source files"],
        )

        return self.revise(
            plan,
            RevisionRequest(
                reason=(
                    "Impact analysis found no extension point for the requested change, "
                    "so the original plan would have implemented against a seam that does "
                    "not exist. Inserting a refactor stage ahead of implementation."
                ),
                add=[seam],
                remove=set(),
                rewire={IMPLEMENT: [DESIGN, REFACTOR]},
            ),
        )


def _rationale(problem: EngineeringProblem, brownfield: bool) -> str:
    parts = [
        f"Scenario: {problem.scenario.value}.",
        f"Analyst confidence: {problem.confidence:.2f}.",
        "Implementation, test authoring and documentation are independent given the "
        "design, so they run concurrently; verification joins them.",
    ]
    if brownfield:
        parts.append(
            "Brownfield change touches an existing public surface, so implementation "
            "is marked high impact and requires human approval before it runs."
        )
    return " ".join(parts)
