"""The three scenarios the assignment asks for, as data rather than prose.

Keeping them here rather than in a shell script means the committed evidence in
`runs/` can be regenerated by anyone, and means the scenarios are covered by the
test suite like everything else.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from keel.models import ScenarioKind


@dataclass(slots=True)
class Scenario:
    key: str
    title: str
    requirement: str
    expects: ScenarioKind
    demonstrates: list[str]
    # Answers a human gives when the run parks. Present only for the ambiguous
    # scenario, where the point is that the run resumes rather than restarts.
    answers: dict[str, str] = field(default_factory=dict)
    # Scripted human decisions so the committed run is reproducible.
    approvals: dict[str, bool] = field(default_factory=dict)
    # Brownfield operates on what greenfield produced.
    seed_from: str | None = None


GREENFIELD = Scenario(
    key="greenfield",
    title="Build a URL shortener from nothing",
    # Deliberately specified to the level a real ticket would be. The first
    # draft of this was vaguer, and the analyst correctly refused to plan it,
    # asking who may create links and whether redirect protection is an
    # allowlist or a denylist. Both are security-posture questions with no
    # defensible default, so the honest fix was to answer them here rather
    # than to loosen the analyst until it stopped noticing.
    requirement=(
        "Build a URL shortener service as a JSON HTTP API using FastAPI and SQLite.\n\n"
        "Endpoints: POST /api/links creates a short link from a long URL and returns "
        "the short code. GET /{code} redirects a visitor to the original URL. "
        "GET /api/links/{code}/stats returns click analytics for that link. "
        "GET /health returns service health.\n\n"
        "Access: link creation is unauthenticated for this release. There is no user "
        "or API-key subsystem and analytics are public. Abuse is handled by per-IP "
        "rate limiting on creation, not by authentication.\n\n"
        "Open redirect protection is a denylist, not an allowlist. Any public http or "
        "https destination is permitted. Reject any other scheme, and reject any "
        "destination resolving to a loopback, private or link-local address, including "
        "the cloud metadata address. The service must never fetch the destination itself.\n\n"
        "Expiry: a caller may pass an expiry; when omitted the link expires 30 days "
        "after creation. Requests for an expired link return 410 Gone.\n\n"
        "Analytics: total click count plus timestamp, referrer and user agent per click. "
        "Do not store visitor IP addresses.\n\n"
        "Short codes are randomly generated, not sequential, so that links cannot be "
        "enumerated."
    ),
    expects=ScenarioKind.GREENFIELD,
    demonstrates=[
        "decomposition of a clear requirement into a dependency graph",
        "parallel execution of implementation, test authoring and documentation",
        "a real pytest run as the verification gate, not a claimed one",
    ],
)

BROWNFIELD = Scenario(
    key="brownfield",
    title="Add rate limiting to the existing shortener",
    requirement=(
        "Add per-API-key rate limiting to the existing URL shortener. Callers "
        "exceeding their quota must receive HTTP 429 with a Retry-After header. "
        "Existing clients must keep working unchanged."
    ),
    expects=ScenarioKind.BROWNFIELD,
    demonstrates=[
        "codebase reasoning: impacted modules, routes and data flows",
        "change control: modifying a public surface requires human approval",
        "dynamic re-planning when analysis contradicts the original plan",
    ],
    approvals={"implement": True, "refactor-seam": True},
    seed_from="greenfield",
)

AMBIGUOUS = Scenario(
    key="ambiguous",
    title="An underspecified requirement",
    requirement="Make the links more secure.",
    expects=ScenarioKind.AMBIGUOUS,
    demonstrates=[
        "detecting that a requirement cannot be planned",
        "parking in the A2A input_required state instead of guessing",
        "writing zero code until a human answers",
        "resuming from the park rather than starting over",
    ],
    answers={
        "What does secure mean here": (
            "Block the service being used for phishing: reject javascript:, data: "
            "and file: schemes, and reject targets resolving to private or "
            "link-local addresses."
        ),
        "Should links require authentication": "No. Creation stays open for now.",
        "Do links need to expire": "Yes, default 30 days, caller may override.",
        "Is scanning destinations for malware in scope": "No, out of scope.",
    },
)

ALL: dict[str, Scenario] = {s.key: s for s in (GREENFIELD, BROWNFIELD, AMBIGUOUS)}


def get(key: str) -> Scenario:
    try:
        return ALL[key]
    except KeyError:
        raise SystemExit(
            f"unknown scenario {key!r}. choose one of: {', '.join(ALL)}"
        ) from None
