"""The three scenarios the assignment asks for, as data rather than prose.

Keeping them here rather than in a shell script means the committed evidence in
`runs/` can be regenerated by anyone, and means the scenarios are covered by the
test suite like everything else.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from keel.models import ScenarioKind


@dataclass(slots=True)
class Scenario:
    key: str
    title: str
    requirement: str
    expects: ScenarioKind
    demonstrates: list[str]
    # Answers a human gives when the run parks. Present only for the ambiguous
    # scenario, where the point is that the run resumes rather than restarts.
    answers: dict[str, str] = field(default_factory=dict)
    # Scripted human decisions so the committed run is reproducible.
    approvals: dict[str, bool] = field(default_factory=dict)
    # Brownfield operates on what greenfield produced.
    seed_from: str | None = None


GREENFIELD = Scenario(
    key="greenfield",
    title="Build a URL shortener from nothing",
    # Deliberately specified to the level a real ticket would be. The first
    # draft of this was vaguer, and the analyst correctly refused to plan it,
    # asking who may create links and whether redirect protection is an
    # allowlist or a denylist. Both are security-posture questions with no
    # defensible default, so the honest fix was to answer them here rather
    # than to loosen the analyst until it stopped noticing.
    requirement=(
        "Build a URL shortener service as a JSON HTTP API using FastAPI and SQLite.\n\n"
        "Endpoints: POST /api/links creates a short link from a long URL and returns "
        "the short code. GET /{code} redirects a visitor to the original URL. "
        "GET /api/links/{code}/stats returns click analytics for that link. "
        "GET /health returns service health.\n\n"
        "Access: link creation is unauthenticated for this release. There is no user "
        "or API-key subsystem and analytics are public. Abuse is handled by per-IP "
        "rate limiting on creation, not by authentication.\n\n"
        "Open redirect protection is a denylist, not an allowlist. Any public http or "
        "https destination is permitted. Reject any other scheme, and reject any "
        "destination resolving to a loopback, private or link-local address, including "
        "the cloud metadata address. The service must never fetch the destination itself.\n\n"
        "Expiry: a caller may pass an expiry; when omitted the link expires 30 days "
        "after creation. Requests for an expired link return 410 Gone.\n\n"
        "Analytics: total click count plus timestamp, referrer and user agent per click. "
        "Do not store visitor IP addresses.\n\n"
        "Short codes are randomly generated, not sequential, so that links cannot be "
        "enumerated."
    ),
    expects=ScenarioKind.GREENFIELD,
    demonstrates=[
        "decomposition of a clear requirement into a dependency graph",
        "parallel execution of implementation, test authoring and documentation",
        "a real pytest run as the verification gate, not a claimed one",
    ],
)

BROWNFIELD = Scenario(
    key="brownfield",
    title="Add rate limiting to the existing shortener",
    # Specified against the system it modifies, which the first draft was not.
    # It asked for per-API-key limiting on a service the greenfield requirement
    # had deliberately made unauthenticated, and the analyst correctly refused
    # to plan it: there was nowhere for a key to come from. Naming the key
    # source and the fallback is what makes the change coherent.
    requirement=(
        "Add per-API-key rate limiting to the existing URL shortener.\n\n"
        # The example deliberately avoids a quoted assignment. An earlier
        # wording spelled it as NAME="alpha:100,beta:20", which the secret
        # scanner reads as a hardcoded credential and blocked, costing a full
        # Opus retry on the design stage. Illustrating the format without the
        # assignment shape is the cheaper honest fix.
        "Keys come from the environment, not from the database. The variable "
        "SHORTENER_API_KEYS holds a comma-separated list of key:quota pairs, so "
        "a key named alpha with a quota of 100 and a key named beta with a "
        "quota of 20 are written as two such pairs. The quota is requests per "
        "minute for link creation. There is no admin surface and no schema "
        "change; an unknown key is treated as no key.\n\n"
        "A caller presents its key in an X-API-Key header. A request carrying a "
        "known key is limited against that key's quota. A request with no key, "
        "or an unknown one, keeps the existing per-IP limit exactly as it "
        "behaves today, so existing clients continue to work unchanged.\n\n"
        "A caller over its quota receives HTTP 429 with a Retry-After header "
        "giving whole seconds until the window resets.\n\n"
        # An earlier wording said only "redirects are not rate limited", and
        # the analyst refused to plan it: the service already throttles
        # redirects per IP, so that sentence could mean "remove that" or "do
        # not extend key limiting to it". It read the existing rate limiter and
        # caught the contradiction, which is the codebase reasoning this
        # scenario is meant to exercise. Saying which one is meant is the fix.
        "This change is additive. The existing per-IP throttle on redirects "
        "stays exactly as it is; do not remove or weaken it. Per-key limiting "
        "applies only to link creation, and redirects are never limited by key."
    ),
    expects=ScenarioKind.BROWNFIELD,
    demonstrates=[
        "codebase reasoning: impacted modules, routes and data flows",
        "change control: modifying a public surface requires human approval",
        "dynamic re-planning when analysis contradicts the original plan",
    ],
    approvals={"implement": True, "refactor-seam": True},
    seed_from="greenfield",
)

AMBIGUOUS = Scenario(
    key="ambiguous",
    title="An underspecified requirement",
    requirement="Make the links more secure.",
    expects=ScenarioKind.AMBIGUOUS,
    demonstrates=[
        "detecting that a requirement cannot be planned",
        "parking in the A2A input_required state instead of guessing",
        "writing zero code until a human answers",
        "resuming from the park rather than starting over",
    ],
    # A human answering the questions, not a lookup table keyed to them.
    #
    # The first version of this matched answers to question text, which only
    # worked until the analyst phrased a question differently. It re-derives
    # the questions on every run, so an answer keyed to last run's wording
    # resolves nothing and the resume parks again. What a person actually does
    # is answer the substance, so the clarification covers the decision space
    # rather than the exact sentences.
    answers={
        "What kind of links are these": (
            "Short redirect links. This is a URL shortener, not magic-link "
            "authentication and not document sharing."
        ),
        "Who may use a link": (
            "Anyone holding it. The link is a bearer capability, with no "
            "per-recipient identity check at resolution."
        ),
        "Do already-issued links have to keep working": (
            "No. There is no predecessor system; this is the service being built."
        ),
        "What does secure mean here": (
            "Stop the service being usable for phishing. Reject javascript:, "
            "data: and file: schemes, and reject any destination resolving to a "
            "loopback, private or link-local address, including the cloud "
            "metadata endpoint. Never fetch the destination."
        ),
        "Should creating a link require authentication": (
            "No. Creation stays open, with per-IP rate limiting for abuse."
        ),
        "Do links expire": "Yes. Default 30 days, and the caller may override.",
        "Is scanning destinations against a threat feed in scope": "No.",
    },
)

ALL: dict[str, Scenario] = {s.key: s for s in (GREENFIELD, BROWNFIELD, AMBIGUOUS)}


def get(key: str) -> Scenario:
    try:
        return ALL[key]
    except KeyError:
        raise SystemExit(
            f"unknown scenario {key!r}. choose one of: {', '.join(ALL)}"
        ) from None
